Feat: Made Horizontal scrolling cards
FEC-Spongebob/Atelier-Client pull request #17
Opened 2023-06-23 20:15 UTC by Meade-Reamy

2023-06-23 20:27 UTC, quasitonality requested changes
I think the header element on line 22 of App.js should be refactored into the RelatedCompare component, for better encapsulation

2023-06-23 20:27 UTC, quasitonality commented on my-app/src/App.js
I would suggest putting all component-related elements within in the component itself (referring to the header element on line 22

2023-06-23 20:36 UTC, Meade-Reamy commented on my-app/src/App.js
Ok, moved it to inside the component

2023-06-24 01:04 UTC, quasitonality approved these changes
Looks good! 👍 I see there's a new react package, looking forward to hearing about it in stand-up

2023-06-24 01:06 UTC, merged